begin;

-- Concrete reusable item components. component_key is generated by PostgreSQL;
-- system_seed_code is the idempotent internal seed identity only.
insert into wizard_item_components (system_seed_code, name, description)
values
  ('hero-title', 'Hero Title', 'Primary promotion title.'),
  ('body-text', 'Body Text', 'Multi-line promotional body copy.'),
  ('remark-text', 'Remark Text', 'Short supporting or eyebrow copy.'),
  ('primary-cta', 'Primary CTA', 'Primary action label and destination.'),
  ('content-image', 'Content Image', 'AI, upload, or URL promotional image.'),
  ('logo-image', 'Logo Image', 'Brand logo image.'),
  ('badge-image', 'Badge Image', 'Trust or license badge image.')
on conflict (system_seed_code) do update set
  name = excluded.name, description = excluded.description, status = 'active', updated_at = now();

insert into wizard_item_component_versions (
  component_id, version, status, field_kind, text_type, editor_schema,
  capabilities, image_policy, cta_policy, style_slots, change_note
)
select component.id, 1, 'active', seed.field_kind, seed.text_type,
  seed.editor_schema::jsonb, seed.capabilities::jsonb, seed.image_policy::jsonb,
  seed.cta_policy::jsonb, seed.style_slots::jsonb, 'Initial component seed.'
from (values
  ('hero-title','text','title','{"multiline":true,"maxLength":160}','{"layoutRegions":["copy-primary","copy-secondary","center"]}','{}','{}','[{"slotKey":"titleColor","semanticRole":"accent-color","aiSelectable":true},{"slotKey":"titleSize","semanticRole":"title-size","aiSelectable":true}]'),
  ('body-text','text','multi','{"multiline":true,"maxLength":2000}','{"layoutRegions":["copy-primary","copy-secondary","center"]}','{}','{}','[{"slotKey":"bodyColor","semanticRole":"text-color","aiSelectable":true}]'),
  ('remark-text','text','remark','{"multiline":true,"maxLength":300}','{"layoutRegions":["copy-primary","copy-secondary","center"]}','{}','{}','[{"slotKey":"remarkColor","semanticRole":"muted-color","aiSelectable":true}]'),
  ('primary-cta','cta',null,'{"labelRequired":true,"linkRequired":true}','{"layoutRegions":["copy-primary","copy-secondary","center"]}','{}','{"utmEnabled":true}','[{"slotKey":"ctaBackground","semanticRole":"accent-color","aiSelectable":true},{"slotKey":"ctaRadius","semanticRole":"radius","aiSelectable":true}]'),
  ('content-image','image',null,'{"altText":true}','{"layoutRegions":["media-primary","media-secondary"],"aiImage":true}','{"allowedSources":["ai","file","url"],"promptText":"Create a promotional image without text, logos, buttons, or UI labels.","aspectRatio":"16:9","descriptionEnabled":true}','{}','[{"slotKey":"imageRadius","semanticRole":"radius","aiSelectable":true}]'),
  ('logo-image','image',null,'{"altText":true}','{"layoutRegions":["brand"]}','{"allowedSources":["file","url"],"aspectRatio":"auto"}','{}','[]'),
  ('badge-image','image',null,'{"altText":true}','{"layoutRegions":["trust"]}','{"allowedSources":["file","url"],"aspectRatio":"auto"}','{}','[]')
) as seed(system_seed_code, field_kind, text_type, editor_schema, capabilities, image_policy, cta_policy, style_slots)
join wizard_item_components component on component.system_seed_code = seed.system_seed_code
where not exists (
  select 1 from wizard_item_component_versions version where version.component_id = component.id and version.version = 1
);

insert into promo_design_token_definitions (
  token_key, category, value_type, semantic_role, css_property, required, ai_selectable
) values
  ('--promo-surface','color','color','surface-color','background-color',true,true),
  ('--promo-text','color','color','text-color','color',true,true),
  ('--promo-muted','color','color','muted-color','color',true,true),
  ('--promo-accent','color','color','accent-color','background-color',true,true),
  ('--promo-radius','shape','length','radius','border-radius',true,true),
  ('--promo-shadow','shape','shadow','shadow','box-shadow',true,true),
  ('--promo-title-size','typography','length','title-size','font-size',true,true)
on conflict (token_key) do nothing;

insert into promo_design_token_sets (set_key, name, description)
values
  ('rounded-style','Rounded Style','Soft corners and elevated surfaces.'),
  ('square-style','Square Style','Sharp corners and clear borders.')
on conflict (set_key) do update set name = excluded.name, description = excluded.description, status = 'active';

insert into promo_design_token_set_versions (token_set_id, version, status, source_name, source_hash, change_note)
select token_set.id, 1, 'active', token_set.set_key || '.csv', 'seed-v1', 'Initial design token set.'
from promo_design_token_sets token_set
where token_set.set_key in ('rounded-style','square-style')
  and not exists (select 1 from promo_design_token_set_versions version where version.token_set_id = token_set.id and version.version = 1);

insert into promo_design_token_values (token_set_version_id, token_key, token_value)
select version.id, seed.token_key, seed.token_value
from (values
  ('rounded-style','--promo-surface','#F8FAFC'), ('rounded-style','--promo-text','#111827'),
  ('rounded-style','--promo-muted','#64748B'), ('rounded-style','--promo-accent','#6D5DFB'),
  ('rounded-style','--promo-radius','24px'), ('rounded-style','--promo-shadow','0 18px 48px rgba(15,23,42,0.16)'),
  ('rounded-style','--promo-title-size','48px'),
  ('square-style','--promo-surface','#FFFFFF'), ('square-style','--promo-text','#101010'),
  ('square-style','--promo-muted','#5A5A5A'), ('square-style','--promo-accent','#0057FF'),
  ('square-style','--promo-radius','0px'), ('square-style','--promo-shadow','0 0 0 rgba(0,0,0,0)'),
  ('square-style','--promo-title-size','48px')
) seed(set_key, token_key, token_value)
join promo_design_token_sets token_set on token_set.set_key = seed.set_key
join promo_design_token_set_versions version on version.token_set_id = token_set.id and version.version = 1
on conflict (token_set_version_id, token_key) do update set token_value = excluded.token_value;

-- New sections are deliberately not named after the removed legacy Header/Hero
-- catalogue. They are assembled from pinned item component versions.
insert into wizard_content_sections (
  section_key, name, description, is_required, order_change_allowed, sort_order,
  is_visible_in_wizard, status, version, change_note, ai_design
)
select 'promotionIntro', 'Promotion Intro', 'Primary promotion content assembled from item components.',
  true, true, 10, true, 'active', 1, 'Initial component-composed section.',
  '{"enabled":true,"allowedLayoutVariants":["split-left","split-right","centered-hero"],"imageTarget":"item","imageTargetItemKeys":["visual"],"imageAspectRatio":"16:9"}'::jsonb
where not exists (select 1 from wizard_content_sections where section_key = 'promotionIntro');

insert into wizard_content_section_component_instances (
  section_id, component_version_id, item_key, display_name, is_required, sort_order
)
select section.id, version.id, seed.item_key, seed.display_name, seed.is_required, seed.sort_order
from (values
  ('remark-text','eyebrow','Eyebrow',false,0),
  ('hero-title','title','Title',true,10),
  ('body-text','description','Description',false,20),
  ('content-image','visual','Visual',false,30),
  ('primary-cta','primaryAction','Primary Action',false,40)
) seed(system_seed_code, item_key, display_name, is_required, sort_order)
join wizard_content_sections section on section.section_key = 'promotionIntro' and section.version = 1
join wizard_item_components component on component.system_seed_code = seed.system_seed_code
join wizard_item_component_versions version on version.component_id = component.id and version.status = 'active'
on conflict (section_id, item_key) do nothing;

insert into wizard_form_templates (
  template_key, name, description, status, version, is_default, change_note, design_token_set_version_id
)
select 'default', 'Default Template', 'Default component-composed promotion template.',
  'active', 1, true, 'Initial template seed.', version.id
from promo_design_token_sets token_set
join promo_design_token_set_versions version on version.token_set_id = token_set.id and version.status = 'active'
where token_set.set_key = 'rounded-style'
  and not exists (select 1 from wizard_form_templates where template_key = 'default');

insert into wizard_form_template_sections (
  form_template_id, section_id, section_key, sort_order, is_required, is_visible,
  order_change_allowed, user_reorder_allowed
)
select template.id, section.id, section.section_key, 10, true, true, true, true
from wizard_form_templates template
join wizard_content_sections section on section.section_key = 'promotionIntro' and section.status = 'active'
where template.template_key = 'default' and template.status = 'active'
on conflict (form_template_id, section_key) do nothing;

commit;
